import '@/global.css';

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import { Box, Typography, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import theme from '@/theme';

// ----------------------------------------------------------------------

const roboto = Roboto({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
              <Box component='header'>
                <Typography variant='h1'>Image Annotation Manager Next.js</Typography>
              </Box>
              <Box component='main' sx={{ flexGrow: 1 }}>
                {children}
              </Box>
              <Box component='footer'>Footer</Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
